name: Deploy FastAPI to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Copy files to VM via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          source: "."
          target: "~/app"

      - name: SSH into VM and reload FastAPI via pm2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            sudo apt update
            sudo apt install -y nodejs npm python3-pip

            sudo npm install -g pm2

            cd ~/app
            pip3 install -r requirements.txt

            pm2 start "uvicorn main:app --host 0.0.0.0 --port 80" --name fastapi || pm2 reload fastapi
            pm2 save

            # Automatically configure pm2 to start on boot
            sudo env PATH=$PATH:/usr/bin pm2 startup systemd -u azureuser --hp /home/azureuser